description: OPT_Finetune_Test_E2E

target:
  service: amlk8s
  # run "amlt target list amlk8s" to list the names of available AMLK8s targets
  name: itphyperdgx2cl1
  vc: hai3

environment:
  image: colossalai-opt:latest
  username: colossalaiopt
  registry: colossalaiopt.azurecr.io
    
code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: ../../

data:
  remote_dir: e2e_dataset
  storage_id: input_data

storage:
  input_data:
    storage_account_name: sahagar
    container_name: data
    mount_dir: /mnt/input_data_dir

  output:
    storage_account_name: sahagar
    container_name: amulet-output
    mount_dir: /mnt/output_dir

jobs:
  - name: OPT_Finetune_Job
    sku: 1xG16
    command:
      # code_dir=/tmp/code
      - set -ex
      - export BS=16
      - export MEMCAP=0
      - export GPUNUM=16
      - export MODLE_PATH="facebook/opt-1.3b"
      - cd examples/language/opt
      - torchrun
          --nproc_per_node $${GPUNUM}
          run_clm.py
          --dataset_name wikitext
          --dataset_config_name wikitext-2-raw-v1
          --output_dir /tmp
          --mem_cap $${MEMCAP}
          --model_name_or_path $${MODLE_PATH}
          --per_device_train_batch_size $${BS} 2>&1 | tee /tmp/colo_$${MODEL}_bs_$${BS}_cap_$${MEMCAP}_gpu_$${GPUNUM}.log